'use client';

import { FADE_IN_UP_CONTAINER, FADE_IN_UP_ITEM } from '@/utils/animations.utils';
import { motion } from 'framer-motion';

export default function TermsPage() {
  return (
    <motion.div
      initial="hidden"
      animate="visible"
      variants={FADE_IN_UP_CONTAINER}
      className="min-h-screen w-full px-4 py-8 md:py-14"
    >
      <motion.div variants={FADE_IN_UP_ITEM} className="mx-auto max-w-3xl space-y-6">
        <h1 className="font-edo text-4xl tracking-wide text-[#1A1A1A] uppercase sm:text-5xl">
          Terms &amp; Conditions
        </h1>
        <p className="font-sans text-sm leading-relaxed text-[#666]">
          Transform to Liberation publishes confessions and meditations that members submit. By
          submitting, you confirm you have the right to share the text and, if you upload a
          recording, the voice recording.
        </p>
        <p className="font-sans text-sm leading-relaxed text-[#666]">
          Studio Voice submissions may be edited before publication. Fully narrated submissions are
          reviewed as sent: we either publish that text and recording, or we do not accept them.
        </p>
        <p className="font-sans text-sm leading-relaxed text-[#666]">
          Cover artwork is generated by us from the finished piece. Submission does not guarantee
          publication.
        </p>
        <p className="font-sans text-xs leading-relaxed text-[#888]">
          Full legal terms will be published here. This page is a working stub until the client
          supplies the final Terms &amp; Conditions.
        </p>
      </motion.div>
    </motion.div>
  );
}
